### ISSUE TITLE
enable smart_format for Deepgram's general model, Nova tier.

### ISSUE THREAD

**Issue by composerjk** [hyperaudio/hyperaudio-lite-editor#166]
It looks like [Smart Formatting](https://developers.deepgram.com/docs/smart-format) is currently only enabled for Deepgram's `whisper` models. It would be nice to enable it for the `general` model of the `Nova` tier.

Since I have longer videos (3–4 hours), I might do some initial transcriptions through the Deepgram API on the audio, then import into the editor.

**Comment by maboa** [comment]
Sounds like a good idea! I'll take a look @composerjk

**Comment by composerjk** [comment]
Thanks. Using Deepgram's Nova does seem to be faster than using their Whisper model, from limited testing.

**Comment by maboa** [comment]
This has now been added @composerjk https://github.com/hyperaudio/hyperaudio-lite-editor/pull/176
