### ISSUE TITLE
add option to Import Deepgram JSON

### ISSUE THREAD

**Issue by composerjk** [hyperaudio/hyperaudio-lite-editor#167]
If one could import Deepgram JSON, then we could run the Deepgram processing elsewhere, load in the audio/video file into Hyperaudio Lite Editor, then import that JSON so we could do some manual editing.

Another alternative could be writing a converter between Deepgram JSON and the Hypertranscript JSON.

**Comment by maboa** [comment]
Yes. Interesting @composerjk – I'll take a look.

**Comment by maboa** [comment]
I took a look and get the JSON imported, a further issue is that we have to somehow link it with the audio / video file.

You can see what I mean by trying this branch https://github.com/hyperaudio/hyperaudio-lite-editor/tree/167-deepgram-JSON-import.

Looking at a simple way to associate the media.

**Comment by composerjk** [comment]
The other use case for linking audio / video:

1. Create transcript via the Hyperaudio Lite Editor using audio only.
2. Then, link that transcript to the video for editing purposes.

We're often working on 3+ hour videos. So, using the audio-only track is much better for the transcription process through Deepgram whether going directly or via the Editor.

**Comment by composerjk** [comment]
When I have a spare moment, I'll take a look at the build process for the Editor so I can try it, locally.

**Comment by maboa** [comment]
OK – I pushed a version with the full functionality. I'd like to refactor before releasing however. 

Thanks for explaining your use case. I'm not clear on why you wouldn't run the deepgram processing built into the app. Unless it's because you want to submit audio to DG but edit using the video source?

**Comment by maboa** [comment]
Refactored and now in the testing phase. Again, this is the branch https://github.com/hyperaudio/hyperaudio-lite-editor/tree/167-deepgram-JSON-import

**Comment by composerjk** [comment]
One scenario is what you wrote: submit audio to DG but edit using the video source. When dealing with 2–4 hours of video, there's no reason to send a few GB of video when a few hundred MB of audio would be faster. And there can be some details in the video that make clarifying spelling and other details, easier, at times.

Another couple scenarios:

- Having DG process with different options than provided in the Editor, e.g., using _[Keywords](https://developers.deepgram.com/docs/keywords)_ or their _[Find/Replace](https://developers.deepgram.com/docs/find-and-replace)_ options to help with context processing. Or even processing with _smart_format_ for Nova before being supported in the Editor.
- Automating the initial transcript generation of multiple videos, then using the Editor for manual review and editing.

We currently have 500+ hours of videos to go through, not counting the archives to eventually be digitized nor audio-only archives. I expect review and editing will happen on and off from the production side to the Editor over time, potentially making non-edited versions initially available before there's time for review.

I did manage to make some time to build a copy to test with, earlier. Thanks for the updates.

**Comment by maboa** [comment]
That makes a lot of sense @composerjk – I have now merged this branch into main. Will leave this issue open a while for discussion. Please don't feel obligated,  but if you're looking to help sustain this project we have a Patreon page https://patreon.com/Hyperaudio

**Comment by composerjk** [comment]
Though we're an all-volunteer nonprofit organization, we do try to support projects that we end up using, both by contributing code and funds, when feasible. Will keep the Patreon in mind, down the road.
