### ISSUE TITLE
Documentation for newbies?

### ISSUE THREAD

**Issue by ffimk** [hyperaudio/hyperaudio-lite-editor#226]
Is there any documentation on how to use hyperaudio-lite-editor for newbies? I've installed it on my server and have no idea how to use it. I don't need to use Deepgram as I already have the transcript.

**Comment by maboa** [comment]
[Hyperaudio Lite ](https://github.com/hyperaudio/hyperaudio-lite) is clientside library that runs inside your browser. This repo concerns the editor which uses Hyperaudio Lite under the hood.
