### ISSUE TITLE
Notify the user that the transcription has been completed using the notification() function in JavaScript 

### ISSUE THREAD

**Issue by scarsellifi** [hyperaudio/hyperaudio-lite-editor#69]
I would like to suggest using the notification() function in JavaScript  (https://developer.mozilla.org/en-US/docs/Web/API/Notification) to notify the user that the transcription has been completed . This function can provide a more user-friendly and intuitive way for the user to be informed about the status of the transcription process: using the notification() function would also be a better solution than keeping the page open and constantly checking for updates. It would allow the user to continue using the application or navigate to a different page while the transcription is being processed, without the need to constantly monitor the status.

I believe that this small change can improve the user experience of the application and make it more convenient for the user to use.

Thank you for considering this suggestion.

**Comment by maboa** [comment]
We could also maybe add PWA native notifications.

**Comment by scarsellifi** [comment]
https://github.com/hyperaudio/hyperaudio-lite-editor/pull/143

**Comment by maboa** [comment]
Addressed with https://github.com/hyperaudio/hyperaudio-lite-editor/pull/143
