### ISSUE TITLE
export/import  json file (web component)

### ISSUE THREAD

**Issue by scarsellifi** [hyperaudio/hyperaudio-lite-editor#74]

**Comment by scarsellifi** [comment]
https://github.com/scarsellifi/hyperaudio-lite-editor/pull/new/74-export-import-json

**Comment by scarsellifi** [comment]
pull request: https://github.com/hyperaudio/hyperaudio-lite-editor/pull/75

**Comment by scarsellifi** [comment]
pull requests https://github.com/hyperaudio/hyperaudio-lite-editor/pull/102

**Comment by maboa** [comment]
Should be addressed by https://github.com/hyperaudio/hyperaudio-lite-editor/pull/102
